---
title: "R Notebook"
knit: (function(inputFile, encoding) { 
  rmarkdown::render('project.Rmd', output_dir = './outputs/') })
  
output:
  html_document:
    number_sections: yes
    toc: yes
---

#Installing and loading dependencies

```{r}
library(dplyr)
library(ggplot2)
library(arsenal)
library(janitor)
library(tidyverse)
```

#Reading the csv file

```{r}
sample_data <- read.csv("./outputs/dictionary.csv") 
```

#Converting the data to dataframe

```{r}
df <- as.data.frame(sample_data) 
```

#Summary of the dataframe

```{r}
summary(df)
```

```{r}
a <- df %>% select(1,5,as.integer(4),6,as.double(8))
summary(a)
```

```{r}
plot(x=a$position, y=a$siftpredictionValue, xlab = "position", ylab = "prediction value", main = "Position range with Sift Prediction values 0.05>tolerated, 0.05<damaging")
abline(h=0.05, col="blue", lwd=2)
# For sift, prediction values smaller than 0.05 are predicted as damaging

plot(x=a$position, y=df$polyphen2predictionValue, xlab = "position", ylab = "prediction value", main = "Position range with Polyphen2 Prediction values between 0.00-0.15 benign, 0.15-1.00 possible damaging, 0.85-1.00 damaging")
abline(h=0.15, col="red",lwd=2)# below is predicted as benign, possibly damaged start point
abline(h=0.85, col="purple",lwd=2)# above is predicted as damaging
```

```{r}

b <- df %>% select(as.integer(4),5,6)

df$index <- 1:nrow(df)

qplot(b$originalType,xlab = "Original Aminoacids",ylab = "Total Sequence", main = "Original Aminoacids Distrubutions")# original aminoacid distrubition

qplot(df$index, b$mutatedType,xlab = "Indexes",ylab = "Mutated Aminoacids", main = "Mutated Aminoacids Distrubutions")# mutated type distrubution

qplot(df$siftpredictionType,xlab = "Sift Prediction Types",main = "Sift Result") # sift result distrubition

qplot(df$polyphen2predictionType,xlab = "Polyphen2 Prediction Types", main = "Polyphen 2 Result") # polyphen 2 result distrubution

qplot(df$position,df$mutatedType,xlab = "Positions",ylab = "Mutated Aminoacids", main = "Mutated Aminoacid Locations")# mutated aminoacid locations => white spaces 

```
```{r}

qplot(df$mutatedType, df$description,xlab = "Mutated Aminoacids",ylab = "Descriptions", main = "Descriptions in accordance with the mutated aminoacids")
```


#Reading input files 
```{r}
df <- read.csv("outputs/dictionary.csv")
siftData <- read.delim("inputs/sift predictions.txt")
polyphen2Data <- read.delim("inputs/polyphen predictions.txt")
```
#Process data
```{r}
siftdf<- df[,c(4,5,6,7,8)]
polydf <- df[,c(4,5,6,9,10)]

s2 <- siftdf
p2 <- polydf

damagingsift <- filter(s2, siftpredictionValue<0.05)
damagingpoly <- filter(p2, polyphen2predictionValue>0.85)


#damagingsift
#damagingpoly
 
#siftdf
#polydf
```
#Data comparisons
```{r}
# First graph shows us that every mutation combination is achieved.
ggplot(siftdf) + geom_point(aes(x=originalType, y=mutatedType))
# Second graph shows us that a single mutated aminoacid can be classified as both tolerated or damaging depending on the location of the mutation.
ggplot(siftdf) + geom_point(aes(x=mutatedType, y=siftpredictionType))

```


```{r}
plot(x=df$position, y=df$siftpredictionValue, xlab = "position", ylab = "prediction value", main = "Position range with Sift Prediction values 0.05>tolerated, 0.05<damaging")
abline(h=0.05, col="blue", lwd=2)
# For sift, prediction values smaller than 0.05 are predicted as damaging

x<-df$position
y<-df$polyphen2predictionValue

plot(x, y, xlab = "position", ylab = "prediction value", main = "Position range with Polyphen2 Prediction values between 0.00-0.15 benign, 0.15-1.00 possible damaging, 0.85-1.00 damaging",ylim=c(1.00,0.00))
abline(h=0.15, col="red",lwd=2)# below is predicted as benign, possibly damaged start point
abline(h=0.85, col="purple",lwd=2)# above is predicted as damaging


plot(damagingsift$position,damagingsift$siftpredictionValue, xlab = "position", ylab = "sift prediction values",ylim=c(1.00,0.00), main = "Sift Damaging")

plot(damagingpoly$position,damagingpoly$polyphen2predictionValue, xlab = "position", ylab = "poly prediction values",ylim=c(0.85,1), main = "poly Damaging")

definiteDamageSift <- filter(s2, siftpredictionValue < 0.01)
definiteDamagePoly <- filter(p2, polyphen2predictionValue > 0.999)

# definiteDamagePoly
# definiteDamageSift

plot(definiteDamageSift$position,definiteDamageSift$siftpredictionValue, xlab = "position", ylab = "sift prediction values",ylim=c(1.00,0.00), main = "0.00 Sift Damaging")

plot(definiteDamagePoly$position,definiteDamagePoly$polyphen2predictionValue, xlab = "position", ylab = "poly prediction values",ylim=c(0.85,1), main = "1.00 poly Damaging")

```
#Intersection of sift and polyphen2

```{r}

definiteDamagingIntersection <- inner_join(definiteDamagePoly, definiteDamageSift)
damagingIntersection <- inner_join(damagingpoly, damagingsift)
## only 1.00 and 0.00 -> definitely damaging intersections
# definiteDamagingIntersection
## all possible damaging intersections
# damagingIntersection
## polyphen2 damaging results
# damagingpoly
## sift damaging results
# damagingsift

renamedSift <- rename(damagingsift, PredictionType = siftpredictionType, PredictionValue = siftpredictionValue)
renamedPoly <- rename(damagingpoly, PredictionType = polyphen2predictionType, PredictionValue = polyphen2predictionValue)
## renaming polyphen2 results so that it can be joined with sift results
# renamedPoly
# renamedSift
## thus acquiring the all damaging mutations
fullSickBinded <- rbind(renamedPoly, renamedSift)
# fullSickBinded
```
```{r}
# Combined damaging results of sift and polyphen2 
plot(fullSickBinded$position,fullSickBinded$PredictionValue, xlab = "position", ylab = "prediction values", main = "combined damaging")

```
```{r}

# We are changing values so that we can show it in the graph as a single damaging section
a <- fullSickBinded
a$PredictionValue[a$PredictionValue <= 0.8] <- 1
a$PredictionValue[a$PredictionValue > 0.8] <- 1
# a

# Empty places are where mutations does not occur
plot(x=a$position, y=a$PredictionValue, xlab = "Position", ylab = "PredictionValue")

# This graph plots only the locations that mutation occurs
p <- head(a, 150)
plot(x=p$position, y=p$PredictionValue, xlab = "Position", ylab = "PredictionValue")

# First 150 rows of locations shown in the graph
ggplot(p, aes(x=position, y=PredictionValue)) + geom_point() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + xlab("Positions")

# First 500 rows of data is plotted
c <- head(a, 500)
ggplot(c, aes(x=factor(position), y=PredictionValue)) + geom_point() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + xlab("Positions")
```
```{r}

splittedOriginalAminoacids <- split(a, f=a$originalType)
# splittedOriginalAminoacids$A
# splittedOriginalAminoacids$L

ggplot(splittedOriginalAminoacids$A, aes(splittedOriginalAminoacids$A$position,splittedOriginalAminoacids$A$mutatedType))+geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("A to other aminoacids")

ggplot(splittedOriginalAminoacids$C, aes(splittedOriginalAminoacids$C$position,splittedOriginalAminoacids$C$mutatedType))+geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("C to other aminoacids")

ggplot(splittedOriginalAminoacids$D, aes(splittedOriginalAminoacids$D$position,splittedOriginalAminoacids$D$mutatedType))+geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("D to other aminoacids")

ggplot(splittedOriginalAminoacids$E, aes(splittedOriginalAminoacids$E$position,splittedOriginalAminoacids$E$mutatedType))+geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("E to other aminoacids")
  

ggplot(splittedOriginalAminoacids$L, aes(splittedOriginalAminoacids$L$position,splittedOriginalAminoacids$L$mutatedType))+geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("L to other aminoacids")


ggplot(splittedOriginalAminoacids$W, aes(splittedOriginalAminoacids$W$position,splittedOriginalAminoacids$W$mutatedType))+geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("W to other aminoacids")

```

```{r}
# Finding the specific mutation information 
chosenAminoacidFromA <- splittedOriginalAminoacids$A[splittedOriginalAminoacids$A$position==119, ]
# print(chosenAminoacidFromA)

chosenAminoacidFromW <- splittedOriginalAminoacids$W[splittedOriginalAminoacids$W$position==146, ]
# print(chosenAminoacidFromW)

```

```{r}
#
dfLimited <- head(df, 50)
# By checking with "chosenAminoacidFromLocation", graph below and uniprot it can be seen that Second amino acid "E" has two mutations in the uniprot and also we have those mutations here as well as these mutations  sift and polyphen2 prediction results which are sift:G, K respectively 0.01, 0.02 and  polyphen2: G, K respectively 0.791, 0.538. Both says these mutations are damaging 
chosenAminoacidFromLocation <-dfLimited[dfLimited$position==2,]
# print(chosenAminoacidFromLocation)

ggplot(dfLimited, aes(position,mutatedType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Mutations in accordance with the positions")

# Lets check other mutations of Second amino acid "E"
# 1851-1867
chosenAminoacidFromLocation <-df[df$position==2,]
# print(chosenAminoacidFromLocation)

ggplot(chosenAminoacidFromLocation, aes(position,mutatedType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Second Amino acid E's mutations ")

ggplot(chosenAminoacidFromLocation, aes(mutatedType,siftpredictionType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Second E's sift results")

ggplot(chosenAminoacidFromLocation, aes(mutatedType,polyphen2predictionType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Second E's polyphen2 results")

#For E TO Q We can say that both predictions are okey

```

```{r}
# Conserved positions 2,4,5,8,9,11,12,15,21,22

# Different amino acids from conserved regions 


# LOCATION 4
chosenAminoacidFromLocation <-df[df$position==4,]
# print(chosenAminoacidFromLocation)

ggplot(chosenAminoacidFromLocation, aes(position,mutatedType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Position 4 Conserved Amino acid mutations")

ggplot(chosenAminoacidFromLocation, aes(mutatedType,siftpredictionType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Position 4 Conserved Amino acid Mutation Sift result ")

ggplot(chosenAminoacidFromLocation, aes(mutatedType,polyphen2predictionType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Position 4 Conserved Amino acid Mutation Polyphen2 result ")


# LOCATION 5
chosenAminoacidFromLocation <-df[df$position==5,]
# print(chosenAminoacidFromLocation)

ggplot(chosenAminoacidFromLocation, aes(position,mutatedType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Position 5 Conserved Amino acid mutations")

ggplot(chosenAminoacidFromLocation, aes(mutatedType,siftpredictionType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Position 5 Conserved Amino acid Mutation Sift result ")

ggplot(chosenAminoacidFromLocation, aes(mutatedType,polyphen2predictionType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Position 5 Conserved Amino acid Mutation Polyphen2 result ")




# LOCATION 8
chosenAminoacidFromLocation <-df[df$position==8,]
# print(chosenAminoacidFromLocation)

ggplot(chosenAminoacidFromLocation, aes(position,mutatedType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Position 8 Conserved Amino acid mutations")

ggplot(chosenAminoacidFromLocation, aes(mutatedType,siftpredictionType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Position 8 Conserved Amino acid Mutation Sift result ")

ggplot(chosenAminoacidFromLocation, aes(mutatedType,polyphen2predictionType))+geom_point()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5))+ xlab("Positions")+ylab("MutatedAminoacid")+ggtitle("Position 8 Conserved Amino acid Mutation Polyphen2 result ")
```

































